### ISSUE TITLE
使用方法？

### ISSUE THREAD

**Issue by YJ3F7** [MaNongXiaoGang/taobao201911.github.io#1]

**Comment by vonking** [comment]
在输入对应程序的数字后，程序闪退

**Comment by MaNongXiaoGang** [comment]
> 在输入对应程序的数字后，程序闪退

你是什么机型，用cmd终端执行把报错的截图发给我看一下。

**Comment by MaNongXiaoGang** [comment]
> _没有提供描述。_

项目更新了，用** git clone git@github.com:MaNongXiaoGang/taobao201911.github.io.git**下载

**Comment by YJ3F7** [comment]
小米8  MIUI11  成功使用 感谢大佬分享（

**Comment by vonking** [comment]
> 在输入对应程序的数字后，程序闪退
> 
> 你是什么机型，用cmd终端执行把报错的截图发给我看一下。

![1](https://user-images.githubusercontent.com/43064858/67542809-277d1100-f721-11e9-9573-b308f8aba4fc.png)
vivo x6

**Comment by yolalala** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/36079926/67545851-3f5a9200-f72d-11e9-8bba-b90c49a68c22.png">
<img width="582" alt="image" src="https://user-images.githubusercontent.com/36079926/67545810-189c5b80-f72d-11e9-9efe-bb29e508faea.png">
华为mate20也在输入数字之后闪退了，错误截图如图

**Comment by zhanhongzhao** [comment]
苹果手机好像不能

**Comment by yolalala** [comment]
> 苹果手机好像不能

我在mac的win虚拟机上操作的华为系统

**Comment by MaNongXiaoGang** [comment]
> > 苹果手机好像不能
> 
> 我在mac的win虚拟机上操作的华为系统

试一下小米系统，最新的淘宝app，其它系统还在测试，等会更新

**Comment by MaNongXiaoGang** [comment]
> <img alt="image" width="578" src="https://user-images.githubusercontent.com/36079926/67545851-3f5a9200-f72d-11e9-8bba-b90c49a68c22.png">
> 
> <img alt="image" width="582" src="https://user-images.githubusercontent.com/36079926/67545810-189c5b80-f72d-11e9-9efe-bb29e508faea.png">
> 
> 华为mate20也在输入数字之后闪退了，错误截图如图

更新了，你再试试

**Comment by MaNongXiaoGang** [comment]
> vivo

vivo没有测试，你更新一下代码测试一下。

**Comment by vonking** [comment]
华为荣耀测试：能正常打开淘宝，但是进入的是省钱专区，没有喵币，是我的操作上有问题吗。我是64位的win10

**Comment by MaNongXiaoGang** [comment]
> 华为荣耀测试：能正常打开淘宝，但是进入的是省钱专区，没有喵币，是我的操作上有问题吗。我是64位的win10

我刚才修改了，你再试试，是不同机型的问题。

**Comment by YJ3F7** [comment]
@MaNongXiaoGang 小米8 MIUI11 在最新版本程序中运行到“点击猫咪获取喵币”无反应结果，进入下一步“领喵币”面板中程序退出

**Comment by MaNongXiaoGang** [comment]
> @MaNongXiaoGang小米8 MIUI11在最新版本程序中运行到“点击猫咪获取喵币”无反应结果，进入下一步“领喵币”面板中程序退出

是用的最新版本吗

**Comment by YJ3F7** [comment]
> > @MaNongXiaoGang小米8 MIUI11在最新版本程序中运行到“点击猫咪获取喵币”无反应结果，进入下一步“领喵币”面板中程序退出
> 
> 是用的最新版本吗

是的
